name: SpigotUtils
version: 1.0
main: com.github.mlefeb01.spigotutils.SpigotUtils
author: Matt Lefebvre
website: github.com/mlefeb01
description: Framework designed to make plugin development less verbose