name: SpigotUtils
version: 1.2
main: com.github.mlefeb01.spigotutils.plugin.SpigotUtils
author: Matt Lefebvre
website: github.com/mlefeb01
description: Framework designed to make plugin development less verbose

commands:
  upgrade:
    usage: /upgrade
    description: The command used to open the upgrade menu for upgradable items
  spigotutils:
    usage: /spigotutils
    aliases: [su]
    description: The command used to reload the config